// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABEKlrCsrGB18oSA2p4oL0mQmdEvAeJZM',
    appId: '1:316157333598:web:5a350aa7ca323a4c2064cf',
    messagingSenderId: '316157333598',
    projectId: 'precesion-f73f6',
    authDomain: 'precesion-f73f6.firebaseapp.com',
    storageBucket: 'precesion-f73f6.firebasestorage.app',
    measurementId: 'G-XYGT1S2L80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVVFssdXJRuKRaw4kDMdY_37snJV2BOQ',
    appId: '1:316157333598:android:e23ecf17a92dadb02064cf',
    messagingSenderId: '316157333598',
    projectId: 'precesion-f73f6',
    storageBucket: 'precesion-f73f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8uIxe4GKLsPE98q4ixSiOTwzx5YEmRAM',
    appId: '1:316157333598:ios:6b31a7d51cd238382064cf',
    messagingSenderId: '316157333598',
    projectId: 'precesion-f73f6',
    storageBucket: 'precesion-f73f6.firebasestorage.app',
    iosBundleId: 'com.example.newApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8uIxe4GKLsPE98q4ixSiOTwzx5YEmRAM',
    appId: '1:316157333598:ios:6b31a7d51cd238382064cf',
    messagingSenderId: '316157333598',
    projectId: 'precesion-f73f6',
    storageBucket: 'precesion-f73f6.firebasestorage.app',
    iosBundleId: 'com.example.newApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABEKlrCsrGB18oSA2p4oL0mQmdEvAeJZM',
    appId: '1:316157333598:web:5388664ef54194bd2064cf',
    messagingSenderId: '316157333598',
    projectId: 'precesion-f73f6',
    authDomain: 'precesion-f73f6.firebaseapp.com',
    storageBucket: 'precesion-f73f6.firebasestorage.app',
    measurementId: 'G-MXRX1R9MMQ',
  );
}
